# -*- coding: utf-8 -*-
# Autogenerated on 09:16:59 2017/04/05
# flake8: noqa
from __future__ import absolute_import, division, print_function, unicode_literals


"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/algo/graph
    makeinit.py --modname=ibeis.algo.graph
"""
