# -*- coding: utf-8 -*-
# Autogenerated on 12:05:11 2016/09/14
# flake8: noqa
from __future__ import absolute_import, division, print_function, unicode_literals
from ibeis.algo.smk import match_chips5
from ibeis.algo.smk import smk_pipeline
from ibeis.algo.smk import vocab_indexer


"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/algo/smk
    makeinit.py --modname=ibeis.algo.smk
"""