# -*- coding: utf-8 -*-
# Autogenerated on 13:37:34 2015/12/30
# flake8: noqa
from __future__ import absolute_import, division, print_function, unicode_literals
from ibeis.algo import Config
from ibeis.algo import detect
from ibeis.algo import hots
from ibeis.algo import smk
from ibeis.algo import preproc


"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/algo
    makeinit.py --modname=ibeis.algo
"""
