# -*- coding: utf-8 -*-
# Autogenerated on 18:39:13 2016/02/22
# flake8: noqa
from __future__ import absolute_import, division, print_function, unicode_literals
from ibeis.other import dbinfo
from ibeis.other import duct_tape
from ibeis.other import detectcore
from ibeis.other import detectfuncs
from ibeis.other import detecttrain
from ibeis.other import ibsfuncs


"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/other
    makeinit.py --modname=ibeis.other
"""
