from __future__ import annotations
from collections import OrderedDict

"""
Autogenerated file. Do not edit by hand.
Regenerate with:
    python ibeis/other/autogen_stats_schema.py --write
"""

ANNOT_STATS_KW_DEFAULTS = OrderedDict([
    ('bigstr', False),
    ('hashid', True),
    ('hashid_visual', False),
    ('hashid_uuid', False),
    ('per_name', True),
    ('per_qual', False),
    ('per_vp', True),
    ('per_multiple', True),
    ('per_name_vpedge', False),
    ('per_enc', True),
    ('per_image', False),
    ('enc_per_name', True),
    ('species_hist', False),
    ('case_tag_hist', False),
    ('match_tag_hist', False),
    ('match_state', False),
    ('min_name_hourdist', False),
])

ANNOTCONFIG_STATS_EXTRA_KW_DEFAULTS = OrderedDict([
    ('combined', False),
    ('combo_gt_info', True),
    ('combo_enc_info', False),
    ('combo_dists', True),
    ('split_matchable_data', True),
])

ANNOTCONFIG_STATS_KW_DEFAULTS = OrderedDict(list(ANNOT_STATS_KW_DEFAULTS.items()) + list(ANNOTCONFIG_STATS_EXTRA_KW_DEFAULTS.items()))
