# -*- coding: utf-8 -*-
"""Development helper to generate a static stats/config schema registry.

This replaces brittle runtime source introspection in production with a checked-in
module that is regenerated manually during development.

CommandLine:
    python ibeis/other/autogen_stats_schema.py
    python ibeis/other/autogen_stats_schema.py --write
"""
from __future__ import absolute_import, division, print_function, unicode_literals
import ast
import sys
from pathlib import Path


REGEN_NOTE = (
    'Autogenerated file. Do not edit by hand.\n'
    'Regenerate with:\n'
    '    python ibeis/other/autogen_stats_schema.py --write\n'
)


class SchemaExtractionError(RuntimeError):
    pass


class StatsSchemaExtractor(object):
    """Conservative extractor for the current stats/config use case.

    This intentionally supports only the simple patterns that exist today.
    If the implementation becomes more dynamic later, update this extractor
    instead of silently guessing.
    """

    def __init__(self, module_fpath=None):
        if module_fpath is None:
            module_fpath = Path(__file__).with_name('ibsfuncs.py')
        self.module_fpath = Path(module_fpath)
        self.source = self.module_fpath.read_text()
        self.module = ast.parse(self.source, filename=str(self.module_fpath))

    def find_funcdef(self, name):
        for node in self.module.body:
            if isinstance(node, ast.FunctionDef) and node.name == name:
                return node
        raise SchemaExtractionError('Cannot find function {!r}'.format(name))

    def parse_default(self, node):
        try:
            return ast.literal_eval(node)
        except Exception:
            pass

        if isinstance(node, ast.BoolOp) and isinstance(node.op, ast.Or) and len(node.values) == 2:
            left, right = node.values
            if isinstance(left, ast.Constant) and isinstance(left.value, bool):
                if isinstance(right, ast.Name) and right.id == 'forceall':
                    return left.value

        raise SchemaExtractionError(
            'Unsupported default expression: {}'.format(
                ast.dump(node, include_attributes=False)
            )
        )

    def extract_kwargs_pop_defaults(self, func_node, kwarg_name='kwargs'):
        found = []
        for node in ast.walk(func_node):
            if not isinstance(node, ast.Call):
                continue
            if not isinstance(node.func, ast.Attribute):
                continue
            if node.func.attr != 'pop':
                continue
            if not isinstance(node.func.value, ast.Name):
                continue
            if node.func.value.id != kwarg_name:
                continue
            if len(node.args) != 2:
                raise SchemaExtractionError(
                    'Expected {}.pop(key, default) in {}'.format(kwarg_name, func_node.name)
                )
            key = ast.literal_eval(node.args[0])
            default = self.parse_default(node.args[1])
            found.append((key, default))
        return found

    def extract_named_defaults(self, func_node, exclude=None):
        exclude = set(exclude or [])
        args = func_node.args.args
        defaults = func_node.args.defaults
        offset = len(args) - len(defaults)
        found = []
        for arg, default in zip(args[offset:], defaults):
            if arg.arg in exclude:
                continue
            found.append((arg.arg, self.parse_default(default)))
        return found

    def extract(self):
        stats_func = self.find_funcdef('get_annot_stats_dict')
        annotconfig_func = self.find_funcdef('get_annotconfig_stats')
        annot_stats = self.extract_kwargs_pop_defaults(stats_func, kwarg_name='kwargs')
        annotconfig_extra = self.extract_named_defaults(
            annotconfig_func, exclude={'verbose'}
        )
        return annot_stats, annotconfig_extra


def _format_ordered_dict_block(name, items):
    lines = []
    lines.append('{} = OrderedDict(['.format(name))
    for key, default in items:
        lines.append('    ({!r}, {!r}),'.format(key, default))
    lines.append('])')
    return '\n'.join(lines)


def make_generated_source(module_fpath=None):
    extractor = StatsSchemaExtractor(module_fpath=module_fpath)
    annot_stats, annotconfig_extra = extractor.extract()
    parts = [
        'from __future__ import annotations',
        'from collections import OrderedDict',
        '',
        '"""',
        REGEN_NOTE.rstrip(),
        '"""',
        '',
        _format_ordered_dict_block('ANNOT_STATS_KW_DEFAULTS', annot_stats),
        '',
        _format_ordered_dict_block('ANNOTCONFIG_STATS_EXTRA_KW_DEFAULTS', annotconfig_extra),
        '',
        'ANNOTCONFIG_STATS_KW_DEFAULTS = OrderedDict(list(ANNOT_STATS_KW_DEFAULTS.items()) + list(ANNOTCONFIG_STATS_EXTRA_KW_DEFAULTS.items()))',
        '',
    ]
    return '\n'.join(parts)


def write_generated_module(dst_fpath=None):
    if dst_fpath is None:
        dst_fpath = Path(__file__).with_name('_autogen_stats_schema.py')
    dst_fpath = Path(dst_fpath)
    text = make_generated_source()
    dst_fpath.write_text(text)
    return dst_fpath


if __name__ == '__main__':
    write = '--write' in sys.argv
    text = make_generated_source()
    if write:
        dst_fpath = write_generated_module()
        print('wrote {!r}'.format(str(dst_fpath)))
    else:
        print(text)
