# -*- coding: utf-8 -*-
# Autogenerated on 15:42:03 2016/04/18
# flake8: noqa
from __future__ import absolute_import, division, print_function, unicode_literals
from ibeis.algo.detect import grabmodels
from ibeis.algo.detect import randomforest
from ibeis.algo.detect import yolo
# from ibeis.algo.detect import selectivesearch
# from ibeis.algo.detect import ssd
# from ibeis.algo.detect import fasterrcnn
# from ibeis.algo.detect import darknet


"""
Regen Command:
    cd /Users/bluemellophone/code/ibeis/ibeis/algo/detect
    makeinit.py --modname=ibeis.algo.detect
"""
