# -*- coding: utf-8 -*-
# Autogenerated on 21:16:37 2016/03/14
# flake8: noqa
from __future__ import absolute_import, division, print_function, unicode_literals
from ibeis.templates import generate_notebook
from ibeis.templates import notebook_cells


"""
Regen Command:
    cd /home/joncrall/code/ibeis/ibeis/templates
    makeinit.py --modname=ibeis.templates
"""
